# GOAL: To run the continuous integration (CI) for this project

name: CI

on:
    push:
        branches:
            - main

jobs:
    code-lint-and-test:
        uses: ./.github/workflows/lint-and-test.yml


    build-and-push:
        secrets: inherit
        needs: code-lint-and-test
        uses: ./.github/workflows/docker.yml