# GOAL: cicd workflow

name: CICD

on:
    # push:
    #     branches:
    #         - main
    workflow_dispatch:


jobs:
    code-lint-and-test:
        uses: ./.github/workflows/lint-and-test.yml

    build-and-push:
        secrets: inherit
        needs: code-lint-and-test
        uses: ./.github/workflows/docker.yml

    deploy:
        needs: [code-lint-and-test, build-and-push]
        uses: ./.github/workflows/deploy.yml