# GOAL: to scan the dynamic running application

name: DAST

on:
    workflow_call:


jobs:
    dast:
        runs-on: ubuntu-latest

        strategy:
          matrix:
            project: [frontend, backend]

        steps:
            - name: Code Checkout
              uses: actions/checkout@v7

            - name: Wait for services to be healthy
              run: |
                timeout 120s sh -c 'until curl -s http://${{ secrets.EC2_HOST }}:5173 > /dev/null; do sleep 2; done'
            
            
            # Scan the running application 
            - name: OWASP ZAP Baseline Scan
              uses: zaproxy/action-baseline@v0.14.0
              with:
                token: ${{ secrets.GITHUB_TOKEN }}
                target: 'http://${{ secrets.EC2_HOST }}:5173'
                fail_action: false
                allow_issue_writing: false

