# GOAL: Deploy the application using docker compose

name: Deploy


on:
    workflow_call:
        
jobs:
    deploy:
        runs-on: self-hosted

        steps:
            - name: Code Checkout
              uses: actions/checkout@v7

            # - name: Docker Login
            #   uses: docker/login-action@v4
            #   with:
            #     username: ${{ vars.DOCKER_USERNAME }}
            #     password: ${{ secrets.DOCKER_TOKEN }}

            - name: Login to dhi.io
              uses: docker/login-action@v4
              with:
                registry: dhi.io
                username: ${{ vars.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_TOKEN }}

            - name: Create environment file
              env:
                POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
                POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
                POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
              run: |
                cat > .env <<EOF
                POSTGRES_DB=$POSTGRES_DB
                POSTGRES_USER=$POSTGRES_USER
                POSTGRES_PASSWORD=$POSTGRES_PASSWORD
                EOF

            # - name: Pull Docker Images
            #   run: docker compose pull

            - name: Start Application
              run: docker compose up -d