# GOAL: provide security before test, lint and deployment left shift

name: DevSecOps

on:
    push:
        branches:
            - main

jobs:

    secret-scan:
        secrets: inherit
        uses: ./.github/workflows/secrets-scanning.yml

    code-lint-and-test:
        needs: secret-scan
        uses: ./.github/workflows/lint-and-test.yml

    sast-scan:
        secrets: inherit
        needs: code-lint-and-test
        uses: ./.github/workflows/sonar-scan.yml

    dependency-scan:
        needs: sast-scan
        uses: ./.github/workflows/dependency_scan.yml

    build-and-scan:
        secrets: inherit
        needs: dependency-scan
        uses: ./.github/workflows/trivy_scans.yml

    docker-push:
        secrets: inherit
        needs: build-and-scan
        uses: ./.github/workflows/docker_push.yml

    deploy:
        secrets: inherit
        needs: docker-push
        uses: ./.github/workflows/deploy.yml

    dast:
        secrets: inherit
        needs: deploy
        uses: ./.github/workflows/dast_scan.yml