# GOAL: 

name: secret-scan

on:
    workflow_call:

jobs:
    secret-scan:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v7
              with:
                fetch-depth: 0

            - name: Scan for leaks
              uses: gitleaks/gitleaks-action@v3
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                GITLEAKS_CONFIG: .github/gitleaks.toml